# Generated by Django 5.2 on 2025-04-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortuary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=100, unique=True)),
                ('payment_type', models.CharField(choices=[('BURIAL', 'Burial Service'), ('PLOT', 'Plot Purchase'), ('MORTUARY', 'Mortuary Services'), ('TRANSPORT', 'Transport Services')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('paid_by', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortuary.deceasedrecord')),
            ],
        ),
    ]
