# Generated by Django 5.2 on 2025-04-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mortuary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('reserved_by', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=50)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mortuary.deceasedrecord')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cemetery.plot')),
            ],
        ),
    ]
